# データベース設定
spring.datasource.url=jdbc:h2:mem:shoppingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2コンソールの設定
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# SQLの初期化設定
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Thymeleafの設定
spring.thymeleaf.cache=false